[application]

# dioxus project name
name = "kiagl"

# default platfrom
# you can also use `dioxus serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "web"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "assets"

[web.app]

# HTML title tag content
title = "kiagl - the website of kappaisagreekletter"

index_on_404 = true

[web.watcher]

watch_path = ["src"]

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["index.css"]

# Javascript code file
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[application.plugins]

available = true

required = []
